version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: g2-wiki-image:latest
    container_name: g2-wiki
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspace:cached
    user: node
