name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy from main to gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set git config
        run: |
          git config --global user.email "g2.yama@gmail.com"
          git config --global user.name "gh-actions"

      - name: Install modules
        run: yarn

      - name: Deploy
        run: yarn deploy
        env:
          GIT_USER: ${{ github.actor }}:${{ github.token }}
